In [2]:
import numpy as np
from Taylor_Test import taylor_test

CG iteration for normal equation

In [9]:
def generateSPDmatrix(n):
    A = np.random.rand(n,n) 
    A = 0.5* (A+A.T)
    
    A = A + n*np.eye(n)
    return A

A=generateSPDmatrix(10)
#np.linalg.eigh(A)       #genreate positive definit matrix A
b=np.random.rand(10)

from Quadratic_solver import conjugate_gradient

conjugate_gradient(A, b).solve(np.ones(10))

CG converged, Error 1.2249842e-14


array([ 0.00298405,  0.00531245,  0.05271618, -0.00544136,  0.04281958,
        0.06346247,  0.0512053 ,  0.00823537, -0.00533938,  0.0611849 ])

In [11]:
#Actual solution 
np.linalg.solve(A,b)

array([ 0.00298405,  0.00531245,  0.05271618, -0.00544136,  0.04281958,
        0.06346247,  0.0512053 ,  0.00823537, -0.00533938,  0.0611849 ])

# Testing differentiability using taylor test 

In [3]:
def f(x):
    return np.sin(x)
def df(x):
    return np.cos(x)
def ddf(x):
    return -np.sin(x)

for i in range(3):
    taylor_test(f,df,ddf, 1, float(1), order =i)

Running Taylor test
Computed residuals: [0.00536085981011869, 0.0026909819076598174, 0.0013481247621756065, 0.0006747203073342867]
Computed convergence rates: [0.9943317168978818, 0.9971786744282893, 0.9985925278897723]
Running Taylor test
Computed residuals: [4.2163248562708186e-05, 1.0529621680881694e-05, 2.631002494743028e-06, 6.575750008880939e-07]
Computed convergence rates: [2.0015324242971615, 2.0007690810629186, 2.000385258427309]
Running Taylor test
Computed residuals: [8.969932231336073e-08, 1.1234370782987885e-08, 1.405667218351557e-09, 1.7579400692479368e-10]
Computed convergence rates: [2.997177761479918, 2.9985923317860106, 2.9992972942682288]


In [4]:
def Rosenbock(x):
    return 100*(x[1]-x[0]**2)**2+(1-x[0])**2
def dRosenbock(x):
    return np.array([2*(200*x[0]**3-200*x[0]*x[1]+x[0]-1), 200*(x[1]-x[0]**2)])
def ddRosenbock(x):
    return np.array([[-400*(x[1]-x[0]**2)+800*x[0]**2+2, -400*x[0]], [-400*x[0], 200]])

taylor_test(Rosenbock, dRosenbock, ddRosenbock, [-1,1],[1,1], order=2)

Running Taylor test
Computed residuals: [0.0005989999999997525, 7.493749999964994e-05, 9.371093749687039e-06, 1.171630859230421e-06]
Computed convergence rates: [2.9987962493807054, 2.9993985011622306, 2.999699344707088]


2.9993985011622306

# Example of a bad convergence of the gradient descent

Example 7.5 in [1]

In [5]:
from Gradient_Descent import unconstrained_opt

def Rosenbock(x):
    return 100*(x[1]-x[0]**2)**2+(1-x[0])**2
def dRosenbock(x):
    return np.array([2*(200*x[0]**3-200*x[0]*x[1]+x[0]-1), 200*(x[1]-x[0]**2)])

solver=unconstrained_opt(Rosenbock,dRosenbock, maxiter=100000)

solver.solve(np.array([-1.2, 1]))

Iteration: 0, Function value: 24.2, Norm of the gradient: 232.86769
Iteration: 1, Function value: 5.1011, Norm of the gradient: 43.898521
Iteration: 2, Function value: 5.047, Norm of the gradient: 45.460144
Iteration: 3, Function value: 4.114, Norm of the gradient: 3.2789771
Iteration: 4, Function value: 4.1081, Norm of the gradient: 3.3509139
Iteration: 5, Function value: 4.1022, Norm of the gradient: 3.41296
Iteration: 6, Function value: 4.0961, Norm of the gradient: 3.4655605
Iteration: 7, Function value: 4.0901, Norm of the gradient: 3.5063758
Iteration: 8, Function value: 4.084, Norm of the gradient: 3.5357514
Iteration: 9, Function value: 4.0779, Norm of the gradient: 3.5522666
Iteration: 10, Function value: 4.0717, Norm of the gradient: 3.556104
Iteration: 11, Function value: 4.0655, Norm of the gradient: 3.5469351
Iteration: 12, Function value: 4.0592, Norm of the gradient: 3.524745
Iteration: 13, Function value: 4.0529, Norm of the gradient: 3.4903555
Iteration: 14, Function v

array([0.99999999, 0.99999998])

Gradient converges to minimum [1,1] after 19227 iterations.

## Gradient descent with Powell Wolfe stepsize 

Algorithm 9.3 in [1]

In [6]:
solver=unconstrained_opt(Rosenbock,dRosenbock, step_size_choice="powell", maxiter=100000)
solver.solve(np.array([-1.2,1]))

Iteration: 0, Function value: 24.2, Norm of the gradient: 232.86769
Iteration: 1, Function value: 5.1011, Norm of the gradient: 43.898521
Iteration: 2, Function value: 5.047, Norm of the gradient: 45.460144
Iteration: 3, Function value: 4.114, Norm of the gradient: 3.2789771
Iteration: 4, Function value: 4.1081, Norm of the gradient: 3.3509139
Iteration: 5, Function value: 4.1022, Norm of the gradient: 3.41296
Iteration: 6, Function value: 4.0961, Norm of the gradient: 3.4655605
Iteration: 7, Function value: 4.0901, Norm of the gradient: 3.5063758
Iteration: 8, Function value: 4.084, Norm of the gradient: 3.5357514
Iteration: 9, Function value: 4.0779, Norm of the gradient: 3.5522666
Iteration: 10, Function value: 4.0717, Norm of the gradient: 3.556104
Iteration: 11, Function value: 4.0655, Norm of the gradient: 3.5469351
Iteration: 12, Function value: 4.0592, Norm of the gradient: 3.524745
Iteration: 13, Function value: 4.0529, Norm of the gradient: 3.4903555
Iteration: 14, Function v

array([0.99999999, 0.99999998])

Convergence after 18713 iterations

# Much better convergence with Newton method

In [8]:
solver=unconstrained_opt(Rosenbock,dRosenbock, ddRosenbock, optimizer="Newton")
solver.solve(np.array([-1.2,1]))

Iteration: 0, Function value: 24.2, Norm of the gradient: 232.86769
Iteration: 1, Function value: 4.7319, Norm of the gradient: 4.6394262
Iteration: 2, Function value: 1.8134, Norm of the gradient: 66.584992
Iteration: 3, Function value: 0.02226, Norm of the gradient: 0.3127286
Iteration: 4, Function value: 0.0086723, Norm of the gradient: 2.7510182
Iteration: 5, Function value: 0.0017115, Norm of the gradient: 0.65985049
Iteration: 6, Function value: 0.00016068, Norm of the gradient: 0.45709671
Iteration: 7, Function value: 1.9266e-06, Norm of the gradient: 0.022363848
Iteration: 8, Function value: 4.2319e-10, Norm of the gradient: 0.00077978321
Iteration: 9, Function value: 1.7391e-17, Norm of the gradient: 6.7580158e-08
Iteration: 10, Function value: 8.288e-29, Norm of the gradient: 1.8207658e-14
Solver Converged!


array([1., 1.])

BFGS (Quasi newtonmethod) fast convergence, without second derivative

In [ ]:
solver=unconstrained_opt(Rosenbock,dRosenbock, optimizer="BFGS", maxiter=2000)
solver.solve(np.array([-1.2,1]))